# Generated by Django 3.2.2 on 2021-05-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelspin', '0002_auto_20210508_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='showed',
            field=models.IntegerField(default=0),
        ),
    ]
