# Generated by Django 3.2.2 on 2021-05-08 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wheelspin', '0005_rooms_showed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='showed',
            field=models.ManyToManyField(blank=True, related_name='showed', to=settings.AUTH_USER_MODEL),
        ),
    ]
