# Generated by Django 3.2.2 on 2021-05-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelspin', '0007_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='charge',
            field=models.IntegerField(default=10),
        ),
    ]
