# Generated by Django 3.2 on 2021-05-20 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wheelspin', '0010_alter_refferuser_refercode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refferuser',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='refferuser',
            name='referCode',
        ),
        migrations.RemoveField(
            model_name='refferuser',
            name='username',
        ),
        migrations.AddField(
            model_name='refferuser',
            name='code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='refferuser',
            name='ref_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refferuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
