# Generated by Django 3.2 on 2021-05-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelspin', '0012_alter_refferuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField()),
            ],
        ),
    ]
